export const networkStatus = Object.freeze({
  NOT_AVAILABLE: 'NOT_AVAILABLE',
  INSTALLING: 'INSTALLING',
  NOT_CONNECTED: 'NOT_CONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  PROCESSING_TRANSACTION: 'PROCESSING_TRANSACTION'
});
