export const INIT_APP = 'INIT_APP';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_ENTITIES = 'SET_ENTITIES';

export const INIT_WEB3 = 'INIT_WEB3';
export const INIT_WEB3_SUCCESS = 'INIT_WEB3_SUCCESS';

export const INIT_ENTITIES = 'INIT_ENTITIES';

export const INSTALL_WALLET = 'INSTALL_WALLET'
export const CONNECT_WALLET = 'CONNECT_WALLET';

export const SET_WALLET = 'SET_WALLET';
export const SET_TRANSACTION = 'SET_TRANSACTION';

export const UPDATE_NETWORK_STATUS = 'UPDATE_NETWORK_STATUS';
export const UPDATE_NETWORK_CHAIN = 'UPDATE_NETWORK_CHAIN';
