export const INIT_APP = 'INIT_APP';
export const INIT_APP_SUCCESS = 'INIT_APP_SUCCESS';
export const CLEANUP = 'CLEANUP';

export const INIT_PLAYBACK = 'INIT_PLAYBACK';
export const PLAY = 'PLAY';
export const PLAY_SUCCESS = 'PLAY_SUCCESS';
export const PLAY_FAIL = 'PLAY_FAIL';
export const STOP = 'STOP';
export const STOP_SUCCESS = 'STOP_SUCCESS';
export const STOP_FAIL = 'STOP_FAIL';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const INIT_WEB3 = 'INIT_WEB3';
export const INIT_WEB3_SUCCESS = 'INIT_WEB3_SUCCESS';
export const INSTALL_WALLET = 'INSTALL_WALLET'
export const CONNECT_WALLET = 'CONNECT_WALLET';
export const SET_WALLET = 'SET_WALLET';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'
export const PROCESS_ACCOUNT_UPDATE = 'PROCESS_ACCOUNT_UPDATE';
export const PROCESS_NETWORK_UPDATE = 'PROCESS_NETWORK_UPDATE';
export const UPDATE_NETWORK_STATUS = 'UPDATE_NETWORK_STATUS';

// USM
export const INIT_USM = 'INIT_USM';
export const SET_TOKENS = 'SET_TOKENS';
export const SET_ACTIVE_ARTIST = 'SET_ACTIVE_ARTIST';
export const SET_ACTIVE_BAND = 'SET_ACTIVE_BAND';
export const FETCH_TOKENS_REQUEST = 'FETCH_TOKENS_REQUEST'
export const FETCH_TOKENS_SUCCESS = 'FETCH_TOKENS_SUCCESS'
export const FETCH_TOKENS_FAIL = 'FETCH_TOKENS_FAIL'
export const FETCH_TOKENS_COMPLETE = 'FETCH_TOKENS_COMPLETE'
export const CREATE_ARTIST_REQUEST = 'CREATE_ARTIST_REQUEST'; 
export const CREATE_ARTIST_SUCCESS = 'CREATE_ARTIST_SUCCESS'; 
export const CREATE_ARTIST_FAIL = 'CREATE_ARTIST_FAIL';
export const START_BAND_REQUEST = 'START_BAND_REQUEST'; 
export const START_BAND_SUCCESS = 'START_BAND_SUCCESS'; 
export const START_BAND_FAIL = 'START_BAND_FAIL';
export const JOIN_BAND_REQUEST = 'JOIN_BAND_REQUEST';
export const CREATE_TRACK_REQUEST = 'CREATE_TRACK_REQUEST'; 
export const CREATE_TRACK_SUCCESS = 'CREATE_TRACK_SUCCESS'; 
export const CREATE_TRACK_FAIL = 'CREATE_TRACK_FAIL';
